### ISSUE TITLE
it's too slow in ios

### ISSUE THREAD

**Issue by CaichaoGitHub** [FaceAR/OpenFaceIOS#11]
While calculating response map , the algorithm cost too much cpu power ,is there any optimized method ??

**Comment by thundertrick** [comment]
@CaichaoGitHub U can try this:
~~~
self.videoCamera.defaultAVCaptureSessionPreset = AVCaptureSessionPreset352x288;
~~~

**Comment by CaichaoGitHub** [comment]
@thundertrick i have read all codes of openface, the key point of why it's so slow is the response map  calculation ;  decrease the resolution is one of optimize methods, however, include that solution, we should consider using gpu power yet ?? cause gpu is very skilled in matrix compulation,i have searched opencv solutions of gpu , but it's pity that opencv was not written for  gpu
