### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by ghost** [FaceAR/OpenFaceIOS#2]
Could you please provide a brief description on how you got this working. 
I know it's still work in progress and I might be able to contribute to improve it  but I need a brief description on how to integrate OpenFace libraries. 

Thanks

**Comment by punkhooren** [comment]
I'm very sorry so long to reply to you, because of the recent busy, I will solve this problem as soon as possible.

**Comment by punkhooren** [comment]
@mosn It's XCode project, just click FaceAR_SDK_IOS_OpenFace_RunFull.xcodeproj and choose you IPhone, and Run.
