### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by whateverx** [FaceAR/OpenFaceIOS#3]
CPU usage is very high, the result is far from 30fps on iPhone 6s
Did you find a way to speed up the process ?

**Comment by realmosn** [comment]
**_BUMP**_
 I am having the same issue. Any solution to fix this ?

**Comment by ivarks** [comment]
I have the same performance issue. Tested on an iPhone5s. The video flows nicely, until the first face detection. After that, it is very slow, even if there aren't any faces in the video. It seems the iPhone uses nearly 100% cpu once the first detection is made.

**Comment by ARGAMX** [comment]
I have the same performance issue on an iPhone5s. Too slow.

**Comment by ARGAMX** [comment]
CPU Time Profiler
http://joxi.net/krDlyyYI08KqQr.jpg

**Comment by ben73** [comment]
Bump

**Comment by ivarks** [comment]
bump

**Comment by sysau** [comment]
bump

**Comment by Jaykob** [comment]
Any news regarding the performance issues?
BTW: I see that you commented out TBB and specifically several `parallel_for`loops. I'm not surprised that this can have a dramatic impact performance wise ;-)

**Comment by mohitsharma0690** [comment]
bump. Is this something that you're looking into or have given up on? 

It would be nice to atleast update the thread and let everyone know the status (even if you're not looking into it atleast somebody else can do it).
