### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by xoxoj** [FaceAR/OpenFaceIOS#4]
![image](https://cloud.githubusercontent.com/assets/1118723/17654949/1760cc68-62db-11e6-859f-5c499e65f8f6.png)

**Comment by whateverx** [comment]
https://github.com/FaceAR/OpenFaceIOS/issues/1

**Comment by punkhooren** [comment]
thanks @whateverx

**Comment by xoxoj** [comment]
can not ...
