### ISSUE TITLE
Face Swap 

### ISSUE THREAD

**Issue by realmosn** [FaceAR/OpenFaceIOS#5]
Hi There, 
Thanks for awesome library, Screenshots shows Face Swap but I can find sample code for that.Could you please take a look

**Comment by whateverx** [comment]
+1 ☺️

**Comment by venky90** [comment]
I also need the same feature.

**Comment by zmw123** [comment]
I also need the same feature.

**Comment by Iragne** [comment]
+1

**Comment by d3github** [comment]
can i have the src code for face swap

**Comment by JanathonL** [comment]
+1☺️
